### ISSUE TITLE
Error on print(datetime.now())

### ISSUE THREAD

**Issue by westernbay** [adafruit/Adafruit_CircuitPython_datetime#23]
I get the error:
AttributeError: type object 'time' has no attribute 'localtime'

Am I supposed to set the local offset from UTC somewhere?

**Comment by FoamyGuy** [comment]
I ran this successfully on a PyGamer with CircuitPython 9.1.0
```
>>> from adafruit_datetime import datetime
>>> print(datetime.now())
2000-01-01 00:32:12
```

Perhaps this was fixed at some point, or is specific only to certain contexts. 

I'm going to close this for now as it appears to work. Please feel free to re-open or create a new issue if you're still having this issue and provide more details like which device, version of CircuitPython, and version of this library that is in use.
