### ISSUE TITLE
Broken fidelity on datetime.fromtimestamp()

### ISSUE THREAD

**Issue by cognitivegears** [adafruit/Adafruit_CircuitPython_datetime#5]
Using datetime.fromtimestamp() is returning incorrect results due to a loss of precision in the underlying EPOC time.  This causes the time to return the same result for multiple seconds, and then "jump", making the seconds value not reliable.

Tested on FeatherS2 and Raspberry Pi Pico.

Steps to reproduce:

    import time
    import adafruit_datetime as datetime
    while True:
        datetime.datetime.fromtimestamp(time.time())
        time.sleep(1)

(observe the time not change second to second)

**Comment by cognitivegears** [comment]
Ok, found out that #4 beat me to the punch on this one. I was comparing with the precompiled version of adafruit_datetime from several days ago, so didn't catch this change. Leaving this here, however, as in the integer case my version avoids an unnecessary conditional and round call, but functionally they are identical so this can be abandoned if you do not feel that it is worth it otherwise.

**Comment by tannewt** [comment]
@jepler What do you think?

**Comment by cognitivegears** [comment]
Made updates to the PR per code review

**Comment by jepler** [comment]
Thank you!
